export const GAME_CONFIG = {
  BOARD_WIDTH: 600,
  BOARD_HEIGHT: 400,
  PLAYER_WIDTH: 10,
  PLAYER_HEIGHT: 50,
  BALL_SIZE: 10,
  PLAYER_VELOCITY: 3,
  PLAYER_OFFSET: 2,
  WINNING_SCORE: 10,
  FPS: 60
} as const;

export const INITIAL_VELOCITY_Y = 2;
export const INITIAL_VELOCITY_X = 2;
